// import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import { Menu, Button } from "@mantine/core";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/carousel/styles.css";
import "@mantine/tiptap/styles.css";
import {
  FaFacebookF,
  FaLinkedinIn,
  FaTwitter,
  FaWhatsapp,
  FaYoutube,
} from "react-icons/fa";
import { GrLocation, GrMailOption } from "react-icons/gr";
import { PiPhoneCallLight } from "react-icons/pi";
import Image from "next/image";
import { MdOutlineKeyboardArrowDown } from "react-icons/md";
import { TbCategoryPlus } from "react-icons/tb";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import NotificationIcon from "@/components/home/notification-icon";
import LoveIcon from "@/components/home/love-icon";
import classes from "@/components/home/login.module.css";
import { IoIosArrowDown } from "react-icons/io";
import Link from "next/link";
import ModalProvider from "@/components/provider/modal-provider";
import {
  QueryClient,
  QueryClientProvider,
  useQuery,
} from "@tanstack/react-query";
import { Toaster } from "react-hot-toast";
import HamburgerMenu from "@/components/common/hamburger-menu";
import { builder } from "@/api/builder";
import NavBar from "@/components/common/navbar";
import { Suspense } from "react";
import Providers from "@/components/provider";

const inter = Inter({
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={poppins.className}>
        <MantineProvider>
          <Providers>
            <ModalProvider>
              <Toaster />
              <main>
                <header className=" py-[11px] bg-purple text-white">
                  <div className="flex max-w-[1400px] mx-auto px-4 justify-between items-center">
                    <section className=" flex items-center gap-[clamp(0.9rem,2vw,1.8rem)] ">
                      <div className=" flex  gap-[10px] items-center ">
                        <GrLocation color="#DAD4FF" size={20} className="" />

                        <p
                          className={`${poppins.className} text-creame text-[14px] font-medium`}
                        >
                          123 Str., Lagos, Nigeria
                        </p>
                      </div>

                      <div className=" flex items-center gap-[9.6px]">
                        <GrMailOption
                          color="#DAD4FF"
                          className="max-[550px]:hidden"
                        />
                        <p
                          className={`${poppins.className} text-creame text-[14px] font-medium max-[550px]:hidden`}
                        >
                          info@pathfinders.com
                        </p>
                      </div>
                    </section>
                    <section className="flex items-center gap-[1.18rem]">
                      <div className=" flex items-center gap-[9.6px]">
                        <PiPhoneCallLight
                          color="#DAD4FF"
                          size={20}
                          className="max-[550px]:hidden "
                        />
                        <p
                          className={`${poppins.className} text-creame text-[14px] font-medium max-[610px]:hidden`}
                        >
                          Call us:
                        </p>
                        <p
                          className={`${poppins.className} text-creame text-[14px] font-medium max-[550px]:hidden`}
                        >
                          234 801234567
                        </p>
                      </div>

                      <div className=" flex gap-[9.6px] items-center max-[883px]:hidden max-[550px]:flex">
                        <p className=" text-[#DAD4FF] text-[14px] font-medium max-[550px]:hidden">
                          Follow Us On :
                        </p>
                        <article className=" flex gap-[9.6px]">
                          <FaFacebookF color="#E7EFFC" size={16} />
                          <FaTwitter color="#E7EFFC" size={16} />
                          <FaWhatsapp color="#E7EFFC" size={18} />
                          <FaLinkedinIn color="#E7EFFC" size={16} />
                          <FaYoutube color="#E7EFFC" size={16} />
                        </article>
                      </div>
                    </section>
                  </div>
                </header>
                <Suspense>
                  <NavBar />
                </Suspense>
                {children}
                <footer className="  bg-purple  py-[37px]">
                  <section className=" mx-auto grid grid-cols-4  max-[816px]:grid-cols-3 justify-between px-4 max-w-[1400px]">
                    <div className=" flex flex-col gap-[13px]">
                      <figure className=" w-[clamp(2.7rem,4.4vw,4.4rem)] h-[clamp(2.7rem,4.4vw,4.4rem)]">
                        <Image
                          className="!h-full !w-full"
                          src="/logo.svg"
                          width={100}
                          height={0}
                          alt="logo"
                        />
                      </figure>
                      <article>
                        <p className=" text-[14px] text-[#B2BBCC] font-medium">
                          123 Street, Lagos, Nigeria
                        </p>
                        <p className=" text-[14px] text-[#B2BBCC] font-medium">
                          +234 801234567
                        </p>
                      </article>
                    </div>
                    <div className=" flex flex-col gap-[20px]">
                      <article className=" flex gap-[16px] flex-col">
                        <h2 className=" text-[20px] font-semibold text-white">
                          Useful Links
                        </h2>
                        <div className=" bg-[#5751E1] h-1 w-[30px] rounded-[2px]"></div>
                      </article>
                      <ul className=" flex flex-col gap-[10px] ">
                        <li className=" text-[#B2BBCC] font-medium text-[14px]">
                          {" "}
                          Our values
                        </li>
                        <li className="text-[#B2BBCC] font-medium text-[14px]">
                          {" "}
                          Our advisory board
                        </li>
                        <li className="text-[#B2BBCC] font-medium text-[14px]">
                          Our partners
                        </li>
                        <li className="text-[#B2BBCC] font-medium text-[14px]">
                          Become a partner
                        </li>
                      </ul>
                    </div>
                    <div className=" flex flex-col gap-[20px]">
                      <article className=" flex gap-[16px] flex-col">
                        <h2 className=" text-[20px] font-semibold text-white">
                          Our Company
                        </h2>
                        <div className=" bg-[#5751E1] h-1 w-[30px] rounded-[2px]"></div>
                      </article>
                      <ul className=" flex flex-col gap-[10px] ">
                        <li className=" text-[#B2BBCC] font-medium text-[14px]">
                          Contact Us
                        </li>
                        <li className="text-[#B2BBCC] font-medium text-[14px]">
                          Become Teacher
                        </li>
                        <li className="text-[#B2BBCC] font-medium text-[14px]">
                          Blog
                        </li>
                        <li className="text-[#B2BBCC] font-medium text-[14px]">
                          Instructor
                        </li>
                        <li className="text-[#B2BBCC] font-medium text-[14px]">
                          Events
                        </li>
                      </ul>
                    </div>
                    <div className=" flex flex-col gap-[20px]">
                      <article className=" flex gap-[16px] flex-col">
                        <h2 className=" text-[20px] font-semibold text-white">
                          Get In Touch
                        </h2>
                        <div className=" bg-[#5751E1] h-1 w-[30px] rounded-[2px]"></div>
                      </article>
                      <section className=" flex flex-col gap-[40px]">
                        <article className=" flex flex-col gap-[18p]">
                          <p className=" text-[#B2BBCC] font-medium text-[14px] w-[229px]">
                            We would like to connect with you, follow us on
                          </p>
                        </article>
                        <article className=" flex gap-[9.6px]">
                          <FaFacebookF color="#E7EFFC" size={16} />
                          <FaTwitter color="#E7EFFC" size={16} />
                          <FaWhatsapp color="#E7EFFC" size={18} />
                          <FaLinkedinIn color="#E7EFFC" size={16} />
                          <FaYoutube color="#E7EFFC" size={16} />
                        </article>
                      </section>
                    </div>
                  </section>
                </footer>
                <section className="bg-[#392A48] py-[35px]">
                  <section className="flex items-center max-w-[1400px] px-4 mx-auto justify-between">
                    <p className="text-base leading-7 text-[#8C9AB4]">
                      &copy; 2024 pathfinders.com. All rights reserved.
                    </p>
                    <div className="flex items-center gap-4">
                      <span className="w-[1px] h-3 bg-[#8C9AB4]" />
                      <p className="text-base leading-7 text-[#8C9AB4]">
                        Privacy Policy
                      </p>
                    </div>
                  </section>
                </section>
              </main>
            </ModalProvider>
          </Providers>
        </MantineProvider>
      </body>
    </html>
  );
}
